language: node_js
dist: precise
node_js:
  - 6.0
notifications:
  email: false
  webhooks:
    urls:
      - https://zulip.org/zulipbot/travis
    on_success: always
    on_failure: always
before_install:
  - npm install
install:
  npm run test
env:
  - COVERALLS_REPO_TOKEN=4eYQDtWoBJlDz2QkxoQ2UcnmJFcOB7zkv
